### ISSUE TITLE
Making server.R more readable

### ISSUE THREAD

**Issue by Saikyun** [samuel-bohman/xplor#2]
Currently server.R is doing a lot of different things of which some could be moved into their own functions, which would improve readability and decrease the risk of breaking breaking code (since you could "encapsule" some of the algorithms).

**Comment by Saikyun** [comment]
I'm currently moving the different parts split up by the comments, moving them into separate functions.
Inside these functions I will then work to make the code more readable, mostly by using Map(...) to group together similar calls (i.e. instead of writing selectInput 50 times I will do something like Map(list, curriedSelectInput) or similar).

**Comment by samuel-bohman** [comment]
I will close this issue as it is somewhat outdated.
